#
# Install PostgreSLQ
#
    
- hosts: "dbhosts"
  become: true
  pre_tasks:
   - pause: seconds=1
   - name: Wait for connection
     wait_for_connection:
       timeout: 600
     ignore_errors: yes
  vars:
    os_packages:
    - https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - postgresql13
    - postgresql13-server
    
    PASSWORD: StrongDBPassword
    LAN: 159.8.91.0/28
      
  tasks:
  
     - name: Install OS packages
       yum:
         name: "{{ os_packages }}"
         state: installed
         
     - name: Add listener address
       ansible.builtin.lineinfile:
         path: /var/lib/pgsql/13/data/postgresql.conf
         line: "listen_addresses = \'{{ ipdb }}\'"
         create: yes
         
     - name: Setup password encryption
       ansible.builtin.lineinfile:
         path: /var/lib/pgsql/13/data/postgresql.conf
         regexp: '^password_encryption ='
         line: password_encryption = md5
         
     - name: Update remote access
       replace:
         path: "/var/lib/pgsql/13/data/pg_hba.conf"
         regexp: '@host    all             all             127.0.0.1/32'
         replace: '@host    all             all             {{ LAN }}'
         backup: yes
     
     - name: Allow old postgresql clients
       replace:
         path: "/var/lib/pgsql/13/data/pg_hba.conf"
         regexp: 'scram-sha-256'
         replace: 'trust'
         backup: yes 
       
       
     - name: Systemctl start/enable postgresql-13
       ansible.builtin.systemd:
         name: postgresql-13
         enabled: yes
         stated: started
         masked: no 
         
     - name: Alter Postgres password
       shell: "psql -c \"alter user postgres with password \'{{ PASSWORD }}\'\""
       become: true
       become_user: postgres   
       
     - name: Alter Postgres password
       shell: "psql -c \"CREATE DATABASE {{ DBNAME }};\""
       become: true
       become_user: postgres   
       
     - name: Download schema
       get_url:
         url: https://github.com/hgrange/pagila/raw/master/pagila-schema.sql
         dest: /root/pagila-schema.sql
         mode: '0644'  
       
     - name: Create schema
       shell: "psql -d {{ DBNAME }} < /root/pagila-schema.sql"
       become: true
       become_user: postgres  
         
            
- hosts: "clienthosts"
  become: true
  pre_tasks:
   - pause: seconds=1
   - name: Wait for connection
     wait_for_connection:
       timeout: 600
     ignore_errors: yes
  
  tasks:
     - name: Install OS packages
       yum:
         name: "postgresql"
         state: installed
         
     - name: Download data to insert
       get_url:
         url: https://github.com/hgrange/pagila/raw/master/pagila-insert-data.sql
         dest: /root/pagila-insert-data.sql
         mode: '0644'     
         
     - name: Insert data
       shell: "PASSWORD={{ PASSWORD }} psql -h {{ ipdb }} -d {{ DBNAME }} < /root/pagila-insert-data.sql"
       become: true
       become_user: postgres  
